<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeFrameworkVersion>8.0.10</RuntimeFrameworkVersion>
    <CodeAnalysisRuleSet>..\..\RavenDB.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Raven.Server\Raven.Server.csproj" />
    <ProjectReference Include="..\..\test\FastTests\FastTests.csproj" />
    <ProjectReference Include="..\..\test\Tests.Infrastructure\Tests.Infrastructure.csproj" />
  </ItemGroup>
</Project>
